name: cicd não produtivo

on:
  pull_request:
    branches: ["release"]
    
jobs: 
  ci:
    runs-on: ubuntu-latest
    
    steps:      
          
      - name: Checkout repository
        uses: actions/checkout@v3
