name: CICD não produtivo

on:
  push:
    branches: ["release"]
    
jobs: 
  CICD:
    runs-on: ubuntu-latest
    
    steps:      
          
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node_version: 16.x

      - name: Install dependencies
        run: npm install
        
      - name: testes
        run: npm run test -- --coverage
        
      - name: sonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Configure SSH Google Cloud
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/google-cloud.key
          chmod 600 ~/.ssh/google-cloud.key
          cat >>~/.ssh/config <<END
          Host google-cloud
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/google-cloud.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.GCP_SSH_USER }}
          SSH_KEY: ${{ secrets.GCP_SSH_KEY }}
          SSH_HOST: ${{ secrets.GCP_SSH_HOST }}
      
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node_version: 16.x

      - name: Install dependencies
        run: npm install
        
      - name: testes
        run: npm run test -- --coverage
        
      - name: sonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: Build the application
        run: npm run build
      
      - name: Deploy the application
        run: | 
            ssh google-cloud sudo systemctl stop react-app
            ssh google-cloud sudo rm -rf react-app/*
            scp -r build google-cloud:/root/app-build
            ssh google-cloud sudo mv app-build/build/* react-app/
            ssh google-cloud sudo systemctl start react-app
